services:
  ollama-image:
    image: ollama-image
    environment:
      - DISPLAY=192.168.0.101:0
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    network_mode: "bridge"
    stdin_open: true
    tty: true 